.github/workflows/review.yml, .github/workflows/test.yml, .golangci.yml, Makefile, cmd/rigs/cmd/local_inventory.go, pkg/builder/builder.go, pkg/dirpublisher/dirpublisher.go, pkg/nftstorage/client.go, pkg/storage/local/impl/store.go, pkg/storage/tableland/impl/files/store.go, pkg/storage/tableland/impl/sqlite/store.go
Spent some time yesterday getting `golangci-lint` updated and setting the recommended rules for the `revive` linter. It worked well, so moved the same setting in this repo.
=> Update linter + fixes

.github/workflows/review.yml, .github/workflows/test.yml
Things were getting confusing with the check names being inconsistent.
=> consistent go version name

README.md, cmd/rigs/cmd/local_view.go
If you didn't manually run `npm install` before, you'd get an error when running `rigs local view`. This runs it for you.
=> Run npm install for viewer

garage/package-lock.json, garage/package.json, garage/src/App.tsx, garage/src/components/RainbowKitTablelandSiweProvider.tsx, garage/src/components/TablelandConnectButton.tsx, garage/src/hooks/useTablelandConnection.ts
Replaces the hacky use of the tableland sdk siwe call in the connect button with a proper `RainbowKitAuthenticationProvider`.
Related, we should maybe look at refactoring the SDK code so that we can re-use the code for auth implementations like this? I had to copy/paste the code we use in the sdk to create the message since we don't expose that code.
=> Fix SIWE implementation

animation_url/src/routes/[slug]/+page.svelte, animation_url/src/routes/[slug]/+page.ts, animation_url/tsconfig.json, animation_url/vite.config.ts
Instead of hard coding the table names, this change will look at the definitions in `ethereum/deployments.ts` for the table definitions.
=> Use single source of truth for deployment tables

garage/package-lock.json, garage/package.json, garage/src/env.ts, garage/src/pages/RigDetails/index.tsx, garage/tsconfig.json, garage/vite.config.ts
- Fixes a dependency issue introduced by dependabot in https://github.com/tablelandnetwork/rigs/pull/311 where wagmi was updated to v0.7.x which is incompatible with our version of rainbowkit. There is a breaking change in the wagmi upgrade v0.6 -> v0.7, I'm gonna work on upgrading the app to use v0.7
- Reads deployment info directly from `ethereum/deployments.ts` instead of the npm package
- Removes the badges section with dummy data from the rig details screen
=> Fix builds, use latest contract deployment & remove badges section with dummy data

cmd/rigs/cmd/publish_layers.go, cmd/rigs/cmd/publish_renders.go, pkg/dirpublisher/dirpublisher.go
Ended up being a stupid bug in processing and using cli flags then properly detecting the empty value of a `cid.Cid`. Also added some flags to make nft.storage upload concurrency and rate limit configurable.
=> Publish layers and renders fix

garage/src/pages/Dashboard/index.tsx, garage/src/pages/Enter.tsx
Fixes a typo in a css calculation + improves text spacing and alignment on the Enter page so that it looks better on mobile.
New:
Old:
=> Garage: minor layout fixes

pkg/storage/local/impl/store.go, pkg/storage/local/store.go, pkg/storage/tableland/impl/tableland/store.go
To clarify, the `gas` column of the `txns` table is the units of gas used, and the `gas_price` column is the cost of each unit of gas in wei (not gwei; 1 gwei = 1,000,000,000 wei).
=> Track gas price in addition to gas used

ethereum/contracts/TablelandRigPilots.sol, ethereum/test/TablelandRigPilots.ts
I think it should be safe to remove the modifier since they don't expose anything sensitive and don't mutate anything? Saves a tiiiny bit of gas for the train/park/pilot calls
=> Remove onlyParent modifier from external view functions

ethereum/deployments.ts
Uses the new attribute value column of `text` type to be compatible with updates to the Tableland SQL spec that don't allow floating point numbers.
New table is `rig_attributes_42161_15`. All the other Arbitrum tables remain the same.
The changes in this PR are only to `artifacts/local.db` which tracks the name of each table on each chain as well as the transaction information from inserting data into the tables.
Closes #420
=> New Rig attributes table on Arbitrum

ethereum/.openzeppelin/polygon-mumbai.json, ethereum/contracts/TablelandRigPilots.sol, ethereum/scripts/verify.ts, ethereum/test/TablelandRigs.ts
The `TablelandRigPilots.sol` contract had a SQL issues that included a missing comma and incorrect `end_time` logic. This fixes these as well as makes the associated changes to the tests, plus, a small fix on the verification script (adds error handling with already verified contracts, which will otherwise halt the verification process).
There were also some slight logic changes when changing a pilot, which now creates a new session instead of morphing an existing trainer session into a "real pilot" session. Lastly, the mumbai contract pilot contract was upgraded to test these logic changes.
=> fix: pilot contract bugs & logic

.github/CODEOWNERS
This is a pretty simple approach, but should help get the right eyes on PRs and reduce noisy GH notifications for all of us. Feel free to suggest changes if you want/don't want to be code owner of a particular directory.
On a side note, doing this made me realize the Go project should be moved to a single sub directory. That might be coming in a PR next...
=> Scope CODEOWNERS to directories

animation_url/src/routes/[slug]/+page.svelte, animation_url/src/routes/[slug]/+page.ts, ethereum/scripts/parkRigs.ts
The alchemy NFT API responses seem to change based on some indexing. eg, a token with GIF media I was testing resulted in a response that had a gateway URI w/ an extension direct from the contract metadata. Rechecking this morning, looks like Alchemy indexed it and included the `format` param and a gateway link without an extension. That broke my parsing, resulting in showing the question mark image.
This changes the logic to use `format` if available and fallback to parsing the URI to determine if the media is an image or video. 
Also switch to using the indexed thumbnail if available.
=> Better media parsing

garage/src/pages/Dashboard/modules/Activity.tsx
Makes the rig image and #id text in the Activity module on the Dashboard clickable links to /rigs/:id
=> Garage: update Dashboard Activity module rows to link to /rigs/:id

garage/src/components/FlyParkModals.tsx, garage/src/pages/Dashboard/modules/RigsInventory.tsx
Not the most amazing user experience but it gets the job done! I think we should add a way to filter Rigs on the dashboard by status later to make it easier to see which rigs you can select. 
In the screenshots below I'm piloting three rigs, so the pilot I'm choosing in step 1 is disabled in 2 etc so that you can't accidentally select the same pilot again.
=> Garage: batch piloting v1

garage/src/App.tsx, garage/src/hooks/useNFTs.ts, garage/src/hooks/useRigStats.ts, garage/src/pages/Dashboard/modules/Stats.tsx, garage/src/utils/queries.ts
Adds tabs to the Stats section on the dashboard, and adds two new tabs with account stats & pilot stats:
This isn't something we have on the current roadmap but it was the top suggestion from the community so it felt right to get that in now :)
@dtbuchholz @sanderpick any suggestions on what to use as labels for the two tables?
=> Garage: add account and pilot stats to Dashboard

garage/src/App.tsx, garage/src/env.ts, garage/src/hooks/useNFTs.ts, garage/src/pages/Dashboard/modules/Activity.tsx, garage/src/pages/OwnerDetails/modules/Activity.tsx, garage/src/pages/RigDetails/index.tsx, garage/src/pages/RigDetails/modules/Pilots.tsx
- Updates all text links on the page to use `text-decoration: underline`
- Moves the "rig header" on /rigs/:id into a separate box/module
- Adds a link to OpenSea to the header on /rigs/:id
- Adds a link to the owner profile to the header on /rigs/:id
Closes https://github.com/tablelandnetwork/rigs/issues/392
=> Garage: Update rig details page with links to opensea and owner profile

garage/src/components/TransferRigModal.tsx, garage/src/contract.json, garage/src/hooks/useNFTs.ts, garage/src/pages/Dashboard/modules/RigsInventory.tsx, garage/src/pages/RigDetails/index.tsx
This PR adds support for transferring a single rig from the /rigs/:id page. It supports both parked and in-flight rigs (using the `safeTransferWhileFlying` method).
This implementation is a bit different than what the issue described. My reasoning:
- I think we should have a way for holders to transfer rigs that are in-flight. If a holder believes that their wallet is compromised or something like that we shouldn't block them from transferring their Rigs in a safe way. The soft-staking kind of works as a protection against theft since a hacker wouldn't be able to transfer assets using a typical bulk transfer contract or by calling `safeTransferFrom` or by sell it via an already approved marketplace, but that only works as long as the owner can transfer it without parking. Moonbirds does …
=> Garage: add support for transferring rigs

garage/src/Topbar.tsx, garage/src/pages/RigDetails/index.tsx
- Moves the topbar search input into a modal on mobile, works much better on small screens and especially if the user doesn't have a wallet connected since that button is much wider than the exit button
- Truncates the `Owned by: <wallet>` address on mobile screens to avoid a horizontal scroll on that view
=> Garage: Improve topbar search input and rig details on mobile

garage/src/pages/OwnerDetails/index.tsx, garage/src/pages/PilotDetails/index.tsx, garage/src/pages/RigDetails/index.tsx
Adds ens support to collector profiles, rig details and pilot details:
Closes https://github.com/tablelandnetwork/rigs/issues/635
=> Garage: ens support

garage/src/components/FlyParkModals.tsx
Fixes the park modal so that it doesn't always warn about training not being complete. The modal looks kind of empty without that text, if you want to add some other text if the rig is trained feel free to @sanderpick 
Closes https://github.com/tablelandnetwork/rigs/issues/646
=> Garage: Fix park modal to check if training is complete before warning about it

garage/src/hooks/useOwnedRigs.ts, garage/src/pages/Dashboard/modules/RigsInventory.tsx, garage/src/utils/queries.ts
Updates the dashboard to use a ✈️ to indicate if a rig is in-flight, and replaces the in-flight text with total FT earned:
instead of
I tried loading the dashboard for the largest holder (`0x6CaB818DAaF4040476E2489A7ED29Ca685aD0623`) and the query still loads fast enough!
Closes https://github.com/tablelandnetwork/rigs/issues/399
=> Garage: Show FT under each rig on dashboard

ethereum/helpers/uris.ts, ethereum/scripts/setURITemplate.ts, ethereum/test/TablelandRigs.ts
When doing some recent work to extend Rigs metadata with Filecoin deal information, I was finding the existing metadata sql query very difficult to further extend since it had already been extended to support Garage status by using the `json_insert` SQLite function. Felt like there must be a better way that supports further metadata extensions without further complicating our use of SQLite JSON functions. Spent a while figuring it out, and landed on this. This query design fits nicely with the to-be-created Filecoin deals table and is overall just easier to read and understand.
=> Use UNION to extend metadata attributes

ethereum/.openzeppelin/polygon-mumbai.json, ethereum/contracts/TablelandRigs.sol, ethereum/contracts/interfaces/IERC4906.sol, ethereum/package-lock.json, ethereum/test/TablelandRigs.ts
- Emits a `MetadataUpdate` event with a `trainRig`, `parkRig`, `pilotRig`, or `parkRigAsOwner` action. This occurs on the `TablelandRigs` contract and not the `TablelandRigPilots`.
- Adds an additional check in `supportsInterface` with the IERC4906 inteface (0x49064906).
- Adds an additional contract in the `interface` directory for the `IERC4906.sol` metadata update.
- Includes a test for metadata update events.
- See the EIP for more details: https://github.com/ethereum/EIPs/blob/master/EIPS/eip-4906.md
- Closes https://github.com/tablelandnetwork/rigs/issues/527
=> feat: add EIP4906 metadata refresh

ethereum/.openzeppelin/polygon-mumbai.json, ethereum/contracts/ITablelandRigPilots.sol, ethereum/contracts/ITablelandRigs.sol, ethereum/contracts/TablelandRigPilots.sol, ethereum/contracts/TablelandRigs.sol, ethereum/deployments.ts, ethereum/test/TablelandRigPilots.ts, ethereum/test/TablelandRigs.ts
This PR fixes an issue where contract and table state diverged due to logic in `parkRig`. It also adds an overloaded `pilotInfo` that can be called with multiple Rig IDs.
The original issue boils down to the following in `parkRig` where an initial `trainingIncomplete` check would `_setPilotData`, separate from the ensuing `UPDATE` statement. 
```solidity
// Pilot training is incomplete; reset the training pilot such that the Rig must train again
if (trainingIncomplete) _setPilotData(uint16(tokenId), 0, 0);
// If the pilot is untrained or being force parked, there are zero flight time rewards
if (trainingIncomplete || force) {
// Update the row in pilot sessions table with its `end_time` equal to the `start_time`
setters = string.concat(
"end_time=",
StringsUpgradeable.toString(startTime) …
```
=> Fix training state mistmatch

animation_url/package-lock.json, animation_url/package.json, ethereum/package-lock.json, ethereum/package.json, garage/package-lock.json, garage/package.json
Rigs interface changed in https://github.com/tablelandnetwork/rigs/pull/720, so we needed a publish to expose them in the garage.
=> Publish and bump rigs in animation_url and garage

garage/src/pages/RigDetails/index.tsx, garage/src/pages/RigDetails/modules/Pilots.tsx
Updates the rig details page to make an on-chain call to `pilotInfo` and to take the contract state into account when deciding which train/pilot button to show. This PR doesn't change the dashboard so it will still show the incorrect action (train instead of pilot) if you select a rig in an inconsistent state, and batch piloting one of those rigs won't work.
Since we know that we only have 20 rigs in this state and we can get 9 fixed by working with one user I think this should be an OK solution. What do you think @sanderpick?
=> Garage: Add RigDetails train/pilot fix for rigs in inconsistent state

.github/workflows/publish.yaml
Adds our standard publish workflow with one difference, the package root used by the actions is the `ethereum/` directory.
fixes https://linear.app/tableland/issue/RIG-33/rigs-npm-package-should-be-deployed-by-github-action
=> Add publish workflow for npm package

ethereum/contracts/DelegateCashMock.sol, ethereum/contracts/ITablelandRigs.sol, ethereum/contracts/TablelandRigs.sol, ethereum/contracts/interfaces/IDelegationRegistry.sol, ethereum/test/TablelandRigs.ts, garage/package-lock.json, garage/package.json, garage/src/App.tsx, garage/src/Topbar.tsx, garage/src/components/ActingAsAddressContext.tsx, garage/src/components/FlyParkModals.tsx, garage/src/hooks/useAccount.ts, garage/src/pages/Dashboard/modules/RigsInventory.tsx, garage/src/pages/Dashboard/modules/Stats.tsx, garage/src/pages/RigDetails/index.tsx
Updates the contract to allow a delegated wallet to train/pilot/park rigs using delegate.cash.
Adds a "Act as" button to the garage top header that is only shown if the currently connected wallet is registered as a delegate for a vault for the Rigs contract. A click on the button lets the user change wallet that they want to make actions for:
Closes RIG-17
=> Add delegate.cash support

garage/package-lock.json, garage/package.json, garage/src/components/FlyParkModals.tsx, garage/src/components/TransferRigModal.tsx, garage/src/hooks/useOwnedRigs.ts, garage/src/pages/OwnerDetails/index.tsx, garage/src/pages/PilotDetails/index.tsx, garage/src/pages/RigDetails/index.tsx, garage/src/polyfills.ts, garage/src/types.ts, garage/src/utils/types.ts
Metamask doesn't allow you to programmatically disconnect a wallet, the user needs to disconnect it themselves. But wagmi has a `shimDisconnect` option that keeps track of the disconnect state locally in the connector using local storage. RainbowKit used to be broken and not pass the correct option to wagmi, but they've fixed that now 
Closes RIG-39
=> Garage: fix wallet disconnect (update rainbowkit & wagmi to 0.12)

garage/package-lock.json, garage/package.json, garage/src/components/FlyParkModals.tsx, garage/src/hooks/useNFTs.ts
A user reported that they weren't able to pilot a rig using a token from the MAX PAIN AND FRENS collection so I looked into it and it turns out that the collection is using token ids larger than `type(uint32).max` (`0xFFFFFF`) which our pilot contract doesn't support because of a packing optimization we made in the pilot info struct (I dunno why they use those IDs, the collection has < 10k tokens but token ids don't start at 0). As I was looking into that I was using the garage as that user and noticed that we weren't filtering out a bunch of garbage tokens from the pilot UI, so I made some tweaks to the piloting UI. 
Changes:
- Filter out airdropped NFTs. The alchemy API does a pretty bad job at filtering out scam NFTs (and doesn't support filtering on ERC721 / ERC1155..), filtering out …
=> Garage: Improve piloting UI

garage/package-lock.json, garage/package.json, garage/src/App.tsx, garage/src/components/FlyParkModals.tsx, garage/src/components/TransactionStateAlert.tsx, garage/src/components/TransferRigModal.tsx, garage/src/hooks/useSigner.ts, garage/src/hooks/useTablelandConnection.ts, garage/src/pages/Admin/index.tsx, garage/src/pages/Dashboard/modules/RigsInventory.tsx, garage/src/pages/PilotDetails/index.tsx, garage/src/pages/RigDetails/index.tsx, garage/src/pages/RigDetails/modules/Pilots.tsx
With `wagmi` moving from `ethers` to `viem`, the `useSigner` hook no longer works. Thus, a custom hook has been created, along with other minor changes due to the dep bump/migration. Also, WalletConnect now requires an API key—it's a `projectId` variable used in the `wagmi` setup and is now accessible as `VITE_WALLET_CONNECT_PROJECT_ID` (env var); this has been added within Vercel as well.
=> feat: migrate to upgraded `wagmi`, `rainbowkit`

garage/src/pages/RigDetails/index.tsx
The selector text has a tooltip (`title` attr) so that you can hover over it and see the full value if it is truncated
=> Garage: fix filecoin modal overflow

garage/api/ft/[from]/[to]/index.ts, garage/vercel.json
Adds a vercel edge function that checks if the amount of FT a wallet has earned is in a given range. The function input/output follows the format of [Vulcan Custom Webhooks](https://help.vulcan.xyz/custom-webhook) so that we can use Vulcan to assign discord roles based on the amount of FT a wallet has earned. The function accepts a range `[from, to)` in the path and expects a JSON-body of `{ "wallet": "<addr>" }`, and returns true if the wallets total FT earned is in that range. This makes it easy to setup multiple different FT-roles in Vulcan so that each user only gest the highest tier role that they qualify for (which makes it clearner imo). I ended up using the gateway api instead of the sdk to make the function startup time faster, based on some local testing it ~25-30% faster to not …
=> Add edge function that checks if a wallets earned ft is in a given range

garage/src/env.ts
The voting contract & ft rewards table is deployed to arbitrum and not filecoin!
Note: this PR is targeting main and not staging, I figured we might as well deploy this right away? And I don't think we have merged anything to staging yet so it would be easy to recreate staging again after this is merged, but feel free to change base to staging as well if you think that is better
=> Garage: fix secondary chain for prod environment

garage/src/hooks/useOwnerVotes.ts, garage/src/hooks/useRigImageUrls.ts, garage/src/pages/OwnerDetails/index.tsx, garage/src/pages/OwnerDetails/modules/RigsInventory.tsx, garage/src/pages/OwnerDetails/modules/Votes.tsx, garage/src/utils/queries.ts
=> Garage: show proposal votes on collector profiles

garage/src/abis/VotingRegistry.ts, garage/src/hooks/useIsAdmin.ts, garage/src/pages/Admin/index.tsx
Adds admin permission checks for proposals & missions. I don't think there is an api for checking if an account has been granted permission to write to a table using `GRANT`, so we can't check if the account can give out ft rewards.
Closes RIG-68
=> Garage: update admin page to check admin permissions

garage/src/hooks/useMissions.ts, garage/src/pages/Mission/index.tsx, garage/src/pages/OwnerDetails/index.tsx, garage/src/pages/OwnerDetails/modules/MBContributions.tsx
=> Garage: Show MB contributions on owner profile page

garage/src/components/ChainAwareButton.tsx, garage/src/components/CreateProposalModal.tsx, garage/src/components/FlyParkModals.tsx, garage/src/components/SubmitMissionModal.tsx, garage/src/pages/Proposal/index.tsx
Fixes an issue where the garage would fail silently if the user was connected to the 'wrong' chain instead of prompting the user to switch chain for certain interactions like submitting a MB contribution
=> Garage: make sure all chain interactions prompt user to switch to correct chain

garage/src/pages/Dashboard/modules/Stats.tsx, garage/src/pages/OwnerDetails/index.tsx, garage/src/pages/PilotDetails/index.tsx, garage/src/pages/RigDetails/index.tsx
if we don't specify a chain it defaults to the currently selected chain which can be arbitrum one in production, and arbitrum doesn't have an ens resolver contract
=> Garage: always resolve ens via mainChain

garage/src/components/ProposalStatusBadge.tsx, garage/src/pages/Dashboard/modules/RigsInventory.tsx, garage/src/pages/PilotDetails/index.tsx, garage/src/pages/Proposal/index.tsx, garage/src/pages/Proposals/index.tsx, garage/src/pages/RigDetails/index.tsx, garage/src/pages/RigDetails/modules/Pilots.tsx
the `useBlockNumber` hook defaults to using the currently connected chains block number but we always want a block number from a specific chain
=> Garage: fix client side block number calculations

garage/src/hooks/useNFTs.ts
Removes the alchemy AIRDROPS filter from useOwnedNFTs, something muyt have changed in alchemy's api because this filter used to work well but now it filters out a lot of non-spam NFTs
=> Garage: Fix listing of owned NFTs when piloting a Rig

garage/src/components/SubmitMissionModal.tsx
Fixes a bug where mission contributions had unescaped single quotes, leading to a query syntax error. This fix just replaces all solo single quotes with two single quotes.
Here's a tx that failed to the workd `they're`: https://tableland.network/api/v1/receipt/42161/0x879420e20419660251d60e31afa148f1bf61c6cdb0173104addde7dd99494871
The fix santizes the values before calling the smart contract:
```js
const sanitizeDeliverables = deliverables.map(({ key, value }) => ({
[key]: value.replace(/\'/g, "''"),
}));
```
Here's a testnet tx that succeeds with the fix & the word `they're` converted to `they''re`: https://mumbai.polygonscan.com/tx/0x4456d2f50ca1c83492ce1f6755389bf8d4224fc384a0638bee57460500b45d19
=> fix: replace single quotes with '' value
