tablelandnetwork/rigs

- ethereum/deployments.ts
This was incorrectly removed in a1b3d6d77827ff93bcaa1da707ccd82bca871e5f
> Add missing pilotSessionsTable to deployment definitions

- ethereum/contracts/ITablelandRigs.sol
- ethereum/contracts/TablelandRigs.sol
- ethereum/contracts/utils/URITemplate.sol
- ethereum/package-lock.json
- ethereum/package.json
Signed-off-by: Sander Pick <sanderpick@gmail.com>
> bump prettier solidity plugin and run format

- cmd/rigs/cmd/publish.go
- pkg/storage/tableland/impl/tableland/store.go
Signed-off-by: Aaron Sutula <asutula@users.noreply.github.com>
> Don't relay, get actual gas used for cost, publish rigs

- go.mod
- go.sum
Signed-off-by: Sander Pick <sanderpick@gmail.com>
> bump go-tableland

- animation_url/package-lock.json
- animation_url/package.json
- ethereum/.openzeppelin/mainnet.json
- ethereum/deployments.ts
- ethereum/package-lock.json
- ethereum/package.json
- garage/package-lock.json
- garage/package.json
- Deploys Pilots and upgrades Rigs on mainnet
- Bumps rigs to `0.1.0`
> Deploy pilots

- animation_url/src/routes/[slug]/+page.ts
Signed-off-by: Sander Pick <sanderpick@gmail.com>
> animation_url: use pinata in prod

- ethereum/.openzeppelin/polygon-mumbai.json
- ethereum/deployments.ts
- ethereum/package-lock.json
- ethereum/scripts/deployPilots.ts
For testing purposes, decreased the required pilot training time to 30 blocks to help ease the testing within The Garage
> chore: new mumbai contracts w/lower training req

- animation_url/.gitignore
- animation_url/src/routes/[slug]/+page.svelte
- animation_url/src/routes/[slug]/+page.ts
Enable vercel to build the animation url for polygon mumbai when in preview mode.
@dtbuchholz I setup this PR to point at the tip of your fix pilot contract branch.  Does that make sense?
> Use vercel env var to determine chain

- animation_url/src/routes/[slug]/+page.svelte
- animation_url/src/routes/[slug]/+page.ts
- use thumbnail when possible
- include check for `image_data`
- handle large svgs
> more animation url tweaks

- garage/src/components/FlyParkModals.tsx
- garage/src/components/RigDisplay.tsx
- garage/src/hooks/useNFTs.ts
So that we default to thumbnails & are consistent with the animation_url
> Garage: update what image url/image data is used for pilots

- garage/src/App.tsx
- garage/src/components/RigAttributeStatsContext.tsx
- garage/src/pages/RigDetails/modules/RigAttributes.tsx
- garage/src/utils/fmt.ts
- garage/src/utils/queries.ts
Closes https://github.com/tablelandnetwork/rigs/issues/401
> Garage: Add trait rarity info to rig details page

- garage/src/Topbar.tsx
- garage/src/hooks/useKeysDown.ts
Closes https://github.com/tablelandnetwork/rigs/issues/397
> Garage: Add rig quick nav search input to top bar

- garage/src/pages/Dashboard/modules/RigsInventory.tsx
- garage/src/pages/Dashboard/modules/Stats.tsx
- garage/src/pages/Enter.tsx
- garage/src/routes.tsx
Closes https://github.com/tablelandnetwork/rigs/issues/543
> Garage: Remove the requirement to have a wallet connected to browse the garage

- ethereum/package.json
Signed-off-by: Aaron Sutula <asutula@users.noreply.github.com>
> Bump ethereum/package.json version

- animation_url/package-lock.json
- animation_url/package.json
This updates the sdk to the official version 4 release.  
One critical fix to safari is included here.
> Update sdk to version 4 official

- garage/src/hooks/useNFTs.ts
- garage/src/pages/Dashboard/index.tsx
- garage/src/pages/OwnerDetails/index.tsx
- garage/src/pages/OwnerDetails/modules/Pilots.tsx
- garage/src/pages/PilotDetails/index.tsx
- garage/src/pages/RigDetails/index.tsx
- garage/src/pages/RigDetails/modules/Pilots.tsx
- garage/src/routes.tsx
- garage/src/types.ts
- garage/src/utils/queries.ts
Adds a detail page for pilots.
Links from RigDetails Pilot module
Closes https://github.com/tablelandnetwork/rigs/issues/395
> Garage: Add Pilot page

- garage/src/components/FlyParkModals.tsx
- garage/src/pages/RigDetails/modules/Pilots.tsx
- garage/src/utils/fmt.ts
Closes https://github.com/tablelandnetwork/rigs/issues/394
> Garage: Update Rig details pilots table to show number of sessions per pilot

- animation_url/package-lock.json
- animation_url/package.json
- ethereum/.openzeppelin/mainnet.json
- ethereum/scripts/upgradePilots.ts
- ethereum/scripts/upgradeRigs.ts
> Ship 1b: Upgrade rigs

- garage/src/hooks/useOwnerActivity.ts
- garage/src/hooks/useRigsActivity.ts
- garage/src/utils/queries.ts
> Garage: improve activity log queries (use UNION to get correct results)

- ethereum/.openzeppelin/mainnet.json
- ethereum/hardhat.config.ts
- ethereum/scripts/parkRigs.ts
- ethereum/scripts/setAdmin.ts
- ethereum/scripts/setURITemplate.ts
- ethereum/scripts/upgradePilots.ts
- ethereum/scripts/upgradeRigs.ts
Upgrades for https://github.com/tablelandnetwork/rigs/pull/714 and https://github.com/tablelandnetwork/rigs/pull/720
> Upgrade pilots and rigs

- .github/dependabot.yml
> dependabot daily -> monthly

- garage/src/Topbar.tsx
> Garage: fix svg error

- animation_url/package-lock.json
- animation_url/package.json
- cmd/rigs/cmd/publish_schema.go
- ethereum/deployments.ts
- ethereum/package-lock.json
- ethereum/package.json
- garage/package-lock.json
- garage/package.json
- garage/src/hooks/useOwnerFTRewards.ts
- garage/src/pages/Admin/index.tsx
- garage/src/pages/OwnerDetails/index.tsx
- garage/src/pages/OwnerDetails/modules/FTRewards.tsx
- garage/src/routes.tsx
- garage/src/types.ts
- garage/src/utils/queries.ts
- pkg/storage/tableland/store.go
Adds a way to give FT to owners for off-chain work.
- Adds a table to track off chain owner rewards (that is created by the rigs cli)
- Updates the garage owner profile with a table that lists FT rewards + updates total FT in header to include rewards
- Adds an /admin page to the garage with a form to insert an ft reward
It doesn't feel like we need a smart contract to own or control writing to the table since we will kind of do that at our own discretion in a centralized way. What do you think @sanderpick?
Closes RIG-15
~Blocked by RIG-36~
> Add a way to give owners FT for off-chain work

- garage/src/env.ts
Updates the code to support multiple deployments. Staging will use the `polygon-mumbai` deployment from the rigs package, and production uses the mainnet deployment.
I've added `VITE_APP_ENV`  env var defs to vercel. All preview deployments (PRs & staging branch) will be using the staging deployment, and prod will use production
Closes RIG-49
> Garage: add support for staging deployment

- animation_url/src/routes/[slug]/+page.ts
Fixes RIG-53 https://linear.app/tableland/issue/RIG-53/update-animation-url-app-to-use-new-rig-image-cids
> Animation url update query

- garage/src/pages/PilotDetails/index.tsx
- garage/src/utils/queries.ts
I noticed a few minor bugs while I was working on https://github.com/tablelandnetwork/rigs/pull/884
> Garage: other minor query fixes

- garage/src/env.ts
- garage/src/hooks/useRigImageUrls.ts
- garage/src/pages/PilotDetails/index.tsx
- garage/src/utils/queries.ts
> Garage: Update queries to use new lookups schemas

- ethereum/contracts/VotingRegistry.sol
- ethereum/scripts/deployVotingRegistry.ts
- ethereum/test/VotingRegistry.ts
Using the GROUP BY-support for INSERT INTO SELECT FROM-queries
> VotingRegistry: update ft snapshotting to only store one row per address and proposal

- ethereum/contracts/VotingRegistry.sol
I think this is the recommended way to name things in case of a conflict https://github.com/ethereum/solidity/issues/11764#issuecomment-1425907973
> VotingRegistry: fix name redeclaration warning

- garage/package-lock.json
- garage/package.json
`npm audit` was complaining that we had 1 high severity vulnerability (in vite so probably 0% risk)
> Garage: update deps

- garage/src/hooks/useProposal.ts
- garage/src/pages/Proposal/index.tsx
Changes:
- Adds explanation to why the user isn't eligible to vote (you had 0 ft at the time of the snapshot)
- Updates the proposal page to refresh the data & display a succes toast after the user has voted
- Adds a tooltip to the Voting reward text that explains that rewards are distributed after the proposal ends
- Updates the vote button-title to 'Update Vote' if the user has already voted
+ a few small bug fixes
> Garage: voting fixes

- animation_url/package-lock.json
- animation_url/package.json
- ethereum/package-lock.json
- ethereum/package.json
- garage/package-lock.json
- garage/package.json
Bump rigs package to 0.3.2 and updates garage and animation url apps.
> Rigs 0.3.2

- garage/src/hooks/useRigImageUrls.ts
> Garage: update rig image urls to use cid subdomain urls

- garage/api/ft/[from]/[to]/index.ts
> Garage: update ft checker vercel function to support both a single wallet and multiple wallets

- animation_url/package-lock.json
- animation_url/package.json
- ethereum/deployments.ts
- ethereum/package-lock.json
- ethereum/package.json
- ethereum/scripts/deployMissionBoard.ts
- ethereum/scripts/verify.ts
- garage/package-lock.json
- garage/package.json
- Deploys mission contract and table to arbitrum (contract is verified)
- Bumps rigs to 0.3.3 and updates garage and animation url apps
Fixes SHI-211
Fixes SHI-210
Fixes SHI-214
> Deploy missions

- garage/src/pages/Admin/index.tsx
> Garage: refresh admin data after creating new entry

- pkg/storage/local/impl/store.go
by removing a leftover TODO comment from a sql statement
> Unbreak rigs cli

- garage/src/hooks/useRigStats.ts
- garage/src/pages/Dashboard/modules/Stats.tsx
- garage/src/utils/queries.ts
> Garage: Add FT leaderboard

- ethereum/scripts/getRigsToPark.ts
Switches to Simplehash's API for active listing, filterable by marketplace: https://docs.simplehash.com/reference/listings-by-contract-1
> feat: use simplehash api for blur rigs
